//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeRoleMapping
    {
        public int RowID { get; set; }
        public string EmployeeID { get; set; }
        public string EmployeeRoles { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string CreateUser { get; set; }
    }
}
