//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int RowID { get; set; }
        public string EmployeeID { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public System.DateTime DOB { get; set; }
        public System.DateTime DOJ { get; set; }
        public Nullable<System.DateTime> DOR { get; set; }
        public string PhoneNo { get; set; }
        public string EmailID { get; set; }
        public Nullable<int> UserId { get; set; }
        public int Status { get; set; }
        public string Photo { get; set; }
        public string Picture { get; set; }
        public int DocumentStatus { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string CreateUser { get; set; }
    }
}
