//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CSLERPEntities : DbContext
    {
        public CSLERPEntities()
            : base("name=CSLERPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<EmployeeDesignation> EmployeeDesignations { get; set; }
        public virtual DbSet<EmployeeExperience> EmployeeExperiences { get; set; }
        public virtual DbSet<EmployeeFinancialLimit> EmployeeFinancialLimits { get; set; }
        public virtual DbSet<EmployeePayRevision> EmployeePayRevisions { get; set; }
        public virtual DbSet<EmployeePosting> EmployeePostings { get; set; }
        public virtual DbSet<EmployeeQualification> EmployeeQualifications { get; set; }
        public virtual DbSet<EmployeeRoleMapping> EmployeeRoleMappings { get; set; }
        public virtual DbSet<ERPUser> ERPUsers { get; set; }
        public virtual DbSet<ViewEmployeeDesignation> ViewEmployeeDesignations { get; set; }
        public virtual DbSet<ViewEmployeeDetail> ViewEmployeeDetails { get; set; }
        public virtual DbSet<ViewEmployeeLocation> ViewEmployeeLocations { get; set; }
        public virtual DbSet<ViewEmployeePosting> ViewEmployeePostings { get; set; }
    }
}
