//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewEmployeeDetail
    {
        public int RowID { get; set; }
        public string EmployeeID { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<System.DateTime> DOJ { get; set; }
        public Nullable<System.DateTime> DOR { get; set; }
        public string PhoneNo { get; set; }
        public string EmailID { get; set; }
        public int Status { get; set; }
        public string OfficeID { get; set; }
        public string OfficeName { get; set; }
        public string RegionID { get; set; }
        public string RegionName { get; set; }
        public Nullable<System.DateTime> PostingDate { get; set; }
        public string Department { get; set; }
        public string DepartmentName { get; set; }
        public string ReportingOfficerID { get; set; }
        public string ReportingOfficerName { get; set; }
        public string Designation { get; set; }
        public string DesignationName { get; set; }
        public Nullable<System.DateTime> DesignationDate { get; set; }
        public string Picture { get; set; }
    }
}
